name: Build Reporting

on:
  push:
    paths:
      - Dockerfile
      - aws_vm_env.yml
      - .github/workflows/container_build.yml

env:
  # TODO: Change variable to your image's name.
  SOFTWARE: viroschool
  VERSION: v1.00

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: |
          IMAGETAGGED=ghcr.io/intensive-school-virology-unipv/$SOFTWARE:$VERSION
          docker build --tag $IMAGETAGGED .

      - name: Log into GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login https://ghcr.io -u ${{ secrets.GITPACKAGE_USER }} --password-stdin

      - name: Push image to GitHub Container Registry
        run: |
          IMAGETAGGED=ghcr.io/intensive-school-virology-unipv/$SOFTWARE:$VERSION
          docker push $IMAGETAGGED
